### ISSUE TITLE
After searching for a note, note is not opening.

### ISSUE THREAD

**Issue by middo1** [rubbieKelvin/notes#108]
Also after searching and refreshing the results is still showing.![Screenshot_20230218-005408.jpg](https://user-images.githubusercontent.com/56052889/219818300-3619a94d-429c-416a-af09-4e197270285a.jpg)

**Comment by middo1** [comment]
Sorry I can't help 🤧

**Comment by rubbieKelvin** [comment]
duplicate of #98
