### ISSUE TITLE
Cant signup if there's a '_' in username

### ISSUE THREAD

**Issue by rubbieKelvin** [rubbieKelvin/notes#115]
![image](https://user-images.githubusercontent.com/46853759/219873947-b5402e70-b7c6-49f2-ac15-982a22ec4549.png)
Not sure if I should categorize this as a `uql` bug. `allow_special_characters=False` prevents special characters from making it through. maybe custom validator should suffice

**Comment by rubbieKelvin** [comment]
- remove space from the end
- make username not case sensitive

**Comment by thiyagarajan17** [comment]
please assign the issue.. would love to work on it!

**Comment by rubbieKelvin** [comment]
thanks @thiyagarajan17 , let me know if you need any help 😁
