### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'focus')     at close (ComboBox.vue:61:35)

### ISSUE THREAD

**Issue by middo1** [rubbieKelvin/notes#73]
![image](https://user-images.githubusercontent.com/56052889/169026818-966dc33f-8e56-4484-8fe8-472beebbabdc.png)

**Comment by middo1** [comment]
this happens when i create new notes

**Comment by rubbieKelvin** [comment]
was this from the recent commits? ie. latest version in main?
run `git pull origin main`
